### ISSUE TITLE
Can't register for button click events

### ISSUE THREAD

**Issue by shaftoe** [getsenic/nuimo-raspberrypi-demo#1]
I'm trying using iPhone Nuimo emulator app following the manual steps with Bluez as in the docs, I can connect successfully but apparently I can't register for events:

> \# gatttool -b 47:21:C6:C3:7B:37 -t random -I
[47:21:C6:C3:7B:37][LE]> connect
Attempting to connect to 47:21:C6:C3:7B:37
Connection successful
[47:21:C6:C3:7B:37][LE]> char-write-req 1e 0100
Error: Characteristic Write Request failed: Attribute can't be written

Ideas?

**Comment by larsblumberg** [comment]
Thanks @shaftoe. The emulators have different characteristic handles than the real Nuimo. Will try to provide a fix today!

**Comment by larsblumberg** [comment]
@shaftoe I've updated the [documentation](/getsenic/nuimo-raspberrypi-demo/). Following the instructions you should now be able to talk to both the real Nuimo and any of the [Nuimo emulators](https://senic.com/developers).

Thanks for raising this issue.
