### ISSUE TITLE
Nuimo does not recognize "Fly" gestures

### ISSUE THREAD

**Issue by gierdo** [getsenic/nuimo-raspberrypi-demo#10]
Hi!

I received my nuimo today and set it up with my android devices, as well as my pc running Ubuntu 16.04 (using the raspberrypi-demo). Pretty easy to set up, the device works fine.

However, the nuimo does not recognize Fly gestures. Neither on android, nor on the pc.

Is the sensor broken, or is there some protective film cover on the glass which I am not aware of, because it is applied excellently :)

Ps.: In know that this is probably not the correct place for the issue, but I didn't find a hardware/general support forum.

**Comment by larsblumberg** [comment]
Dear gierdo,
you can activate the fly sensor by touching the sensor (small window on top of Nuimo's surface) for 2 seconds. Please let me know if that helps.

**Comment by gierdo** [comment]
That was quick.

Thank you very much!

Issue resolved. Awesome support!
:+1:
