### ISSUE TITLE
Bluepy import problem

### ISSUE THREAD

**Issue by shaftoe** [getsenic/nuimo-raspberrypi-demo#2]
I've installed bluepy lib as described in the docs:

> $ sudo python setup.py install
running install
running build
running build_py
running install_lib
running install_egg_info
running egg_info
writing bluepy.egg-info/PKG-INFO
writing top-level names to bluepy.egg-info/top_level.txt
writing dependency_links to bluepy.egg-info/dependency_links.txt
writing entry points to bluepy.egg-info/entry_points.txt
reading manifest file 'bluepy.egg-info/SOURCES.txt'
writing manifest file 'bluepy.egg-info/SOURCES.txt'
removing '/usr/local/lib/python2.7/dist-packages/bluepy-0.9.11.egg-info' (and everything under it)
Copying bluepy.egg-info to /usr/local/lib/python2.7/dist-packages/bluepy-0.9.11.egg-info
running install_scripts
Installing sensortag script to /usr/local/bin

For some reason, my Python can't properly load the module

> $ python nuimo.py 47:21:C6:C3:7B:37
Traceback (most recent call last):
  File "nuimo.py", line 1, in <module>
    from bluepy.btle import DefaultDelegate, Peripheral, BTLEException
ImportError: No module named btle

Ideas?

PS testing on a Raspberry Pi 1 model B, kernel v4.1.13+ (Raspian Jessie)

**Comment by larsblumberg** [comment]
Please check if the modules folder is in your PYTHONPATH.

You can verify running this command line:

python -c "import sys; print '/usr/local/lib/python2.7/dist-packages' in sys.path"

**Comment by shaftoe** [comment]
Yes the sys.path is fine. I also have other modules there (e.g. bottle) and I can import them all right. Weird thing is that the statement `import bluepy` works, and `from bluepy import *` also works, but I can't see any available function/class name from dir() output. Looks like I'm importing an empty module, but doesn't look empty to me

> $ pwd
> /usr/local/lib/python2.7/dist-packages/bluepy
> $ cat \__init__.py
> \__all__ = ["btle", "sensortag"]
> $ head btle.py
> #!/usr/bin/env python
> from \__future__ import print_function
> """Bluetooth Low Energy Python interface"""
> import sys
> import os
> import time
> import subprocess
> import binascii

**Comment by larsblumberg** [comment]
Since you are in Berlin, would you mind to swing by our office so that we can have a look onto it together?

**Comment by shaftoe** [comment]
Not so easy to unplug that Rasp but looks like there's finally a good reason for it :+1: 
I've also got a new model of Raspberry Pi that I'd like to use for this, so I'll try on that before to see if the problem persists.
Thanks a lot for your support by the way! I'll drop by anyway to say hi one of those days

**Comment by larsblumberg** [comment]
We are happy to see you back here

**Comment by shaftoe** [comment]
Ok, I think I solved the mystery: Python default loading path include the `current working dir`, meaning that, if you run a Python script that imports `somemodule`, it will look for a folder called like that in search for `__init__.py` and such, and of course they are there into the git clone!

To recap, if you follow the current instructions from 2.1 to 2.6, you could step into the same problem. I suggest to add as step 2.7 to remove completely the bluepy git clone after install is done to avoid this kind of pitfall.

Now I can import the libraries, but I step into another problem, so I think a different issue might fit better

**Comment by larsblumberg** [comment]
TODO: Check this and eventually add a step to remove bluepy folder

**Comment by larsblumberg** [comment]
@shaftoe README updated. Thank you!

**Comment by hardwarewinjit** [comment]
Hi, I am getting the same error message "ImportError no module named bluepy.bluepy.btle". Please help to resolve it

Thanks, 
Shruti

**Comment by larsblumberg** [comment]
@hardwarewinjit: The official Nuimo SDK for Raspi/Linux can be found here: https://github.com/getsenic/nuimo-linux-python – Have you tried this one?

**Comment by shaftoe** [comment]
@larsblumberg great news! Thanks for the heads up. Will try asap and give you feedback
