### ISSUE TITLE
Python script works with real Nuimo device but not yet with emulators

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/nuimo-raspberrypi-demo#3]
Python script works with real Nuimo devices. But when connecting to [Nuimo emulators](https://senic.com/developers#emulator) it won't receive input events.

Fix is in progress and will be published today.

**Comment by larsblumberg** [comment]
Fixed. No works with emulators as well.

**Comment by shaftoe** [comment]
Can't wait to try this out!
