### ISSUE TITLE
Manual connect works but nuimo.py can't connect

### ISSUE THREAD

**Issue by shaftoe** [getsenic/nuimo-raspberrypi-demo#4]
I slightly modified the script to avoid silencing the connect exception, so it can be inspected in the following output. Maybe I'm doing something wrong but I can't spot the error (also running the command as root doesn't change the error)

    $ sudo gatttool -b 7B:B7:B7:7C:24:F2 -t random -I
    [7B:B7:B7:7C:24:F2][LE]> connect
    Attempting to connect to 7B:B7:B7:7C:24:F2
    Connection successful
    [7B:B7:B7:7C:24:F2][LE]> characteristics
    handle: 0x0002, char properties: 0x02, char value handle: 0x0003, uuid: 00002a00-0000-1000-8000-00805f9b34fb
    handle: 0x0004, char properties: 0x02, char value handle: 0x0005, uuid: 00002a01-0000-1000-8000-00805f9b34fb
    handle: 0x0007, char properties: 0x20, char value handle: 0x0008, uuid: 00002a05-0000-1000-8000-00805f9b34fb
    handle: 0x000b, char properties: 0x98, char value handle: 0x000c, uuid: 8667556c-9a37-4c91-84ed-54ee27d90049
    handle: 0x0010, char properties: 0x94, char value handle: 0x0011, uuid: 10000001-328e-0fbb-c642-1aa6699bdada
    handle: 0x0014, char properties: 0x02, char value handle: 0x0015, uuid: 10000002-328e-0fbb-c642-1aa6699bdada
    handle: 0x0017, char properties: 0x02, char value handle: 0x0018, uuid: 20000001-328e-0fbb-c642-1aa6699bdada
    handle: 0x001a, char properties: 0x02, char value handle: 0x001b, uuid: 00002a29-0000-1000-8000-00805f9b34fb
    handle: 0x001d, char properties: 0x88, char value handle: 0x001e, uuid: f29b1524-cb19-40f3-be5c-7241ecb82fd1
    handle: 0x0021, char properties: 0x10, char value handle: 0x0022, uuid: f29b1526-cb19-40f3-be5c-7241ecb82fd2
    handle: 0x0024, char properties: 0x10, char value handle: 0x0025, uuid: f29b1527-cb19-40f3-be5c-7241ecb82fd2
    handle: 0x0027, char properties: 0x10, char value handle: 0x0028, uuid: f29b1528-cb19-40f3-be5c-7241ecb82fd2
    handle: 0x002a, char properties: 0x10, char value handle: 0x002b, uuid: f29b1529-cb19-40f3-be5c-7241ecb82fd2
    handle: 0x002e, char properties: 0x12, char value handle: 0x002f, uuid: 00002a19-0000-1000-8000-00805f9b34fb
    handle: 0x0032, char properties: 0x12, char value handle: 0x0033, uuid: 00002a2b-0000-1000-8000-00805f9b34fb
    handle: 0x0035, char properties: 0x02, char value handle: 0x0036, uuid: 00002a0f-0000-1000-8000-00805f9b34fb
    handle: 0x0038, char properties: 0x02, char value handle: 0x0039, uuid: 00002a29-0000-1000-8000-00805f9b34fb
    handle: 0x003a, char properties: 0x02, char value handle: 0x003b, uuid: 00002a24-0000-1000-8000-00805f9b34fb
    handle: 0x003d, char properties: 0x88, char value handle: 0x003e, uuid: 69d1d8f3-45e1-49a8-9821-9bbdfdaad9d9
    handle: 0x0040, char properties: 0x10, char value handle: 0x0041, uuid: 9fbf120d-6301-42d9-8c58-25e699a21dbd
    handle: 0x0043, char properties: 0x10, char value handle: 0x0044, uuid: 22eac6e9-24d6-4bb5-be44-b36ace7c7bfb
    handle: 0x0047, char properties: 0x98, char value handle: 0x0048, uuid: 9b3c81d8-57b1-4a8a-b8df-0e56f7ca51c2
    handle: 0x004b, char properties: 0x98, char value handle: 0x004c, uuid: 2f7cabce-808d-411f-9a0c-bb92ba96c102
    handle: 0x004f, char properties: 0x8a, char value handle: 0x0050, uuid: c6b2f38c-23ab-46d8-a6ab-a3a870bbd5d7
    [7B:B7:B7:7C:24:F2][LE]> char-write-req 002c 0100
    Characteristic value was written successfully
    Notification handle = 0x002b value: 01
    Notification handle = 0x002b value: 00
    Notification handle = 0x002b value: 01
    Notification handle = 0x002b value: 00
    Notification handle = 0x002b value: 01
    Notification handle = 0x002b value: 00
    Notification handle = 0x002b value: 01
    Notification handle = 0x002b value: 00
    Notification handle = 0x002b value: 01
    Notification handle = 0x002b value: 00
    Notification handle = 0x002b value: 01
    Notification handle = 0x002b value: 00
    [7B:B7:B7:7C:24:F2][LE]>
    $ python nuimo.py 7B:B7:B7:7C:24:F2
    Trying to connect to 7B:B7:B7:7C:24:F2. Press Ctrl+C to cancel.
    Traceback (most recent call last):
      File "nuimo.py", line 88, in <module>
        nuimo.connect()
      File "nuimo.py", line 68, in connect
        self.peripheral.writeCharacteristic(self.characteristicValueHandles[name] + 1, NOTIFICATION_ON, True)
      File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 459, in writeCharacteristic
        return self._getResp('wr')
      File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 334, in _getResp
        resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
      File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 296, in _waitResp
        raise BTLEException(BTLEException.COMM_ERROR, "Error from Bluetooth stack (%s)" % errcode)
    bluepy.btle.BTLEException: Error from Bluetooth stack (comerr)

**Comment by shaftoe** [comment]
I forgot to say, the actual error code suggests this:

    3. Enable BLE: btmgmt le on

but I can't find any btmgmt command available for Debian Jessie

**Comment by larsblumberg** [comment]
There's a similar issue opened here in bluepy: https://github.com/IanHarvey/bluepy/issues/83. It doesn't have a solution as of today.

You can however install `btmgmt`. It's part of bluez and might help here.

Here are the steps to manually install latest bluez:

1. `wget https://www.kernel.org/pub/linux/bluetooth/bluez-5.37.tar.xz`
2. `tar xvf bluez-5.37.tar.xz`
3. `cd bluez-5.37`
4. `sudo apt-get install libudev-dev libical-dev libreadline-dev`
5. `./configure --disable-systemd`
6. `make` (takes very long)
7. `cd tools`
8. `sudo ./btmgmt le on`

**Comment by larsblumberg** [comment]
I'm thinking about replacing bluepy with [pygattlib](https://bitbucket.org/OscarAcena/pygattlib/).

**Comment by shaftoe** [comment]
:+1: for pygattlib, I didn't check the implementation so I can't say from a dev perspective, but it's available via Pip so should make the setup much easier

**Comment by larsblumberg** [comment]
I will give it try next week.

**Comment by mattwelch** [comment]
I was finally able to connect by switching the Nuimo off, then back on, during the nuimo.py connection phase. Perhaps related, I had to do the same thing during lescan for the Nuimo to show up.

**Comment by larsblumberg** [comment]
@mattwelch This is not related. You are running the Nuimo iOS beta app on your phone. It automatically connects to your Nuimo as soon as it turns on. Once connected by your iPhone, it's not discoverable and connectable anymore by any other device. That's why restarting Nuimo makes it discoverable with BLE scan for a few second until your Nuimo app connects again automatically. You to need remove the app from the running apps in order to prevent it from automatically connect. Alternatively, disconnect Nuimo manually on the Nuimo screen. Then it stops auto connecting.

**Comment by Fromss** [comment]
I had the same issue and it worked by removing BATTERY from NOTIFICATION_CHARACTERISTIC_UUIDS
You won't register battery related events, but at least the rest works

**Comment by larsblumberg** [comment]
@Fromss You are using the Nuimo emulator for iOS, right? Just found out that iOS doesn't allow battery notification subscriptions without authentication. So I commented battery notifications by default for now.

Thanks a lot for your hint!

**Comment by Fromss** [comment]
Indeed I was using the iOS emulator. (btw is there any planned addition of fly movements to the emulator ? not having them seriously limit my ability to prepare for the upcoming shipment of my kickstarter nuimo as well as putting something cool together for the nuimo hack...)

**Comment by larsblumberg** [comment]
Yes, fly events will be supported by the emulators very soon. Can't give you a time though as our capacities are limited.
